# fly.toml app configuration file generated for luz-voice-spike on 2026-10-01T05:38:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'luz-voice-spike'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
